# This is a basic workflow to help you get started with Actions

name: Build and Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
        
      - name: Initialize cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Copy
        run: |
          mkdir -v build
          cp -v -r assets build/
          cp -v index.html build/
          cp -v favicon.ico build/

      - name: Compile
        run: |
          if ! [ -d ~/.cargo ]; then curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh; fi
          wasm-pack build --target web -d build/assets/pkg --no-typescript
        
      - name: Cleanup
        run: rm -v build/assets/pkg/{.gitignore,LICENSE,package.json,README.md}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
